# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6b777328-7a9f-4993-9975-dbf108f9bbb9";
      fsType = "btrfs";
      options = [ "subvol=@" "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E92D-47BE";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/be118546-895f-4e8b-8e93-8939d149b1ff";
      fsType = "ext4";
    };

  fileSystems."/home/ayako/Games" =
    { device = "/dev/disk/by-uuid/6b777328-7a9f-4993-9975-dbf108f9bbb9";
      fsType = "btrfs";
      options = [ "subvol=Games" "ssd" "compress=zstd" ];
    };

  swapDevices = [{
    device = "/dev/disk/by-partuuid/c488f151-05";
    randomEncryption.enable = true;
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}